/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
export const JournalEntryData = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mood' : IDL.Int,
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mood' : IDL.Int,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MessageGroup = IDL.Record({ 'messages' : IDL.Vec(Message) });
export const MoodSummary = IDL.Record({
  'date' : IDL.Text,
  'avgMood' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([IDL.Vec(Message)], [], []),
  'addJournalEntry' : IDL.Func([JournalEntryData], [JournalEntry], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessagesForCaller' : IDL.Func([], [IDL.Vec(MessageGroup)], ['query']),
  'getJournalEntriesForCaller' : IDL.Func(
      [],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getMoodSummary' : IDL.Func([], [IDL.Vec(MoodSummary)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({ 'content' : IDL.Text, 'role' : IDL.Text });
  const JournalEntryData = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mood' : IDL.Int,
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mood' : IDL.Int,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MessageGroup = IDL.Record({ 'messages' : IDL.Vec(Message) });
  const MoodSummary = IDL.Record({
    'date' : IDL.Text,
    'avgMood' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([IDL.Vec(Message)], [], []),
    'addJournalEntry' : IDL.Func([JournalEntryData], [JournalEntry], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessagesForCaller' : IDL.Func(
        [],
        [IDL.Vec(MessageGroup)],
        ['query'],
      ),
    'getJournalEntriesForCaller' : IDL.Func(
        [],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getMoodSummary' : IDL.Func([], [IDL.Vec(MoodSummary)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };